# Generated by Django 5.1.7 on 2025-04-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_receitas_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/imagens'),
        ),
    ]
